### PR TITLE
Add support for IPv6

### PR DESCRIPTION
**Pull request by Marsup**
Hello,

Since we're reaching the end of IPv4 blocks, it seems like a good idea to support IPv6.
This modification seems to do the job, but before continuing I wanted to get your feedback on the direction it's taking since it's obviously a breaking change.
Of course you'll need an IPv6 ready network to make the tests pass.

### CODE REVIEW

**Comment by Marsup** [comment]
And it seems travis doesn't support IPv6...

**Comment by sindresorhus** [comment]
Good idea! Is there really any point in getting both at once, though? Having `publicIp.v4()` and `publicIp.v6()` would simplify the API would mean this won't have to be a breaking change, as `publicIp()` could just alias to `publicIp.v4()`.

**Comment by sindresorhus** [comment]
Note to self. This one also need IPv6 support: https://github.com/sindresorhus/internal-ip/issues/2 (help welcome)

**Comment by sindresorhus** [comment]
As for the failing test, maybe try removing `sudo: false` from .travis.yml to use the old non-container system, which might have IPv6 support. Alternatively we could setup CircleCI too: https://github.com/ipfs/go-ipfs/blob/81c64768c59fcd77e82a313894fdd4105d9b0df5/circle.yml#L9-L10

**Comment by Marsup** [comment]
I have the need for both at but it's not truly needed at the module level, I'll cover that from the outside. I'll work on those separate APIs.

**Comment by Marsup** [comment]
OK so it's much slower for travis but at least it works. Is code any good or is it not your style ?

**Comment by sindresorhus** [comment]
Thank you! I added some docs and CLI support in follow-up commits.

**Comment by Marsup** [comment]
Oh yeah, sorry about that, thanks :)

**Comment by sindresorhus** [comment]
No worries. I forgot too.

**Pull request merged**
