### PR TITLE
Don't throw CancelError if ipv6 resolves first

### LINKED ISSUE #69: Unable to handle exception for CancelError
I've been trying to figure out why I am getting an uncaught exception, even though I specifically catch the error originating from public-ip:

```
browser.js:53 Uncaught (in promise) CancelError: Request was cancelled
    at browser.js:53:11
    at new Promise (<anonymous>)
    at sendXhr (browser.js:36:18)
    at browser.js:79:15
    at queryHttps (browser.js:93:2)
    at publicIpv4 (browser.js:105:9)
    at publicIp2 (core.js:13:23)
    at headers (sessions.js?t=1691585655153:8:22)
    at create (sessions.js?t=1691585655153:17:45)
    at Proxy.submitForm (TheSignIn.vue:80:32)
```

```js
const headers = async () => {
  try {
    const ip = await publicIp();
    return { 'X-Forwarded-For': ip };
  } catch (error) {
    return { 'X-Forwarded-For': null };
  }
};
```

### PR DESCRIPTION
**Pull request by Richienb**
Fixes #69

### CODE REVIEW

**Comment by doutatsu** [comment]
Anything I can do to help @Richienb? Would love to get this one sorted, as it's been polluting my error logs for awhile now 😫

**Comment by Richienb** [comment]
@doutatsu Sure, let's collab. If you want, open a pr to https://github.com/Richienb/public-ip/tree/main-1 that adds mocks which cause the ipv4 promise to stall and the ipv6 promise to succeed, then test if its return value is as expected (like in the current tests which imply that no error is thrown).

**Comment by doutatsu** [comment]
I decided to rollback instead for now, as I am a bit swamped to try and look into fixing this.

**Comment by sindresorhus** [comment]
Bump :)

**Comment by Richienb** [comment]
Relatively confident this will work but don't have ipv6 to test it

**Pull request merged**
